apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: smartpark

build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: ghcr.io/cmc197/smartpark-producer
      context: producer
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/cmc197/smartpark-processing
      context: processing
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/cmc197/smartpark-serving
      context: serving
      docker:
        dockerfile: Dockerfile
  local:
    push: true
    useBuildkit: false
    concurrency: 2

manifests:
  helm:
    releases:
      - name: smartpark
        chartPath: deploy/helm
        namespace: smartpark
        createNamespace: true
        valuesFiles:
          - deploy/helm/values.yaml
        setValueTemplates:
          producer.image.repository: "{{.IMAGE_REPO_ghcr_io_cmc197_smartpark_producer}}"
          producer.image.tag: "{{.IMAGE_TAG_ghcr_io_cmc197_smartpark_producer}}"
          spark.image.repository: "{{.IMAGE_REPO_ghcr_io_cmc197_smartpark_processing}}"
          spark.image.tag: "{{.IMAGE_TAG_ghcr_io_cmc197_smartpark_processing}}"
          api.image.repository: "{{.IMAGE_REPO_ghcr_io_cmc197_smartpark_serving}}"
          api.image.tag: "{{.IMAGE_TAG_ghcr_io_cmc197_smartpark_serving}}"

deploy:
  helm: {}

profiles:
  - name: local
    patches:
      - op: replace
        path: /build/local/push
        value: false

  - name: load
    patches:
      - op: add
        path: /manifests/helm/releases/0/setValues
        value:
          producer.replicas: 5
          config.producer.eventRate: 200
